# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hesapmakinesi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(262, 417)
        Dialog.setStyleSheet("background-color: #283637;")
        self.buttonSifirla = QtWidgets.QPushButton(Dialog)
        self.buttonSifirla.setGeometry(QtCore.QRect(20, 110, 50, 50))
        self.buttonSifirla.setStyleSheet("QPushButton {\n"
"    color: #fff; \n"
"    border-radius: 20px;\n"
"    border-style: outset; \n"
"    padding: 5px;\n"
"    background-color: rgb(121, 121, 121);\n"
"    }\n"
" ")
        self.buttonSifirla.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 110, 50, 50))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    color: #fff; \n"
"    border-radius: 20px;\n"
"    border-style: outset; \n"
"    padding: 5px;\n"
"    background-color: rgb(121, 121, 121);\n"
"    }\n"
" ")
        self.pushButton_2.setObjectName("pushButton_2")
        self.buttonArti = QtWidgets.QPushButton(Dialog)
        self.buttonArti.setGeometry(QtCore.QRect(200, 110, 50, 50))
        self.buttonArti.setStyleSheet("QPushButton { \n"
"    border-radius: 20px;\n"
"    border-style: outset; \n"
"    padding: 5px;\n"
"    background-color: #fff;\n"
"    }\n"
" ")
        self.buttonArti.setObjectName("buttonArti")
        self.buttonBol = QtWidgets.QPushButton(Dialog)
        self.buttonBol.setGeometry(QtCore.QRect(200, 230, 50, 50))
        self.buttonBol.setStyleSheet("QPushButton { \n"
"    border-radius: 20px;\n"
"    border-style: outset; \n"
"    padding: 5px;\n"
"    background-color: #fff;\n"
"    }\n"
" ")
        self.buttonBol.setObjectName("buttonBol")
        self.buttonCarp = QtWidgets.QPushButton(Dialog)
        self.buttonCarp.setGeometry(QtCore.QRect(200, 290, 50, 50))
        self.buttonCarp.setStyleSheet("QPushButton { \n"
"    border-radius: 20px;\n"
"    border-style: outset; \n"
"    padding: 5px;\n"
"    background-color: #fff;\n"
"    }\n"
" ")
        self.buttonCarp.setObjectName("buttonCarp")
        self.buttonEksi = QtWidgets.QPushButton(Dialog)
        self.buttonEksi.setGeometry(QtCore.QRect(200, 170, 50, 50))
        self.buttonEksi.setStyleSheet("QPushButton { \n"
"    border-radius: 20px;\n"
"    border-style: outset; \n"
"    padding: 5px;\n"
"    background-color: #fff;\n"
"    }\n"
" ")
        self.buttonEksi.setObjectName("buttonEksi")
        self.buttonHesapla = QtWidgets.QPushButton(Dialog)
        self.buttonHesapla.setGeometry(QtCore.QRect(200, 350, 50, 50))
        self.buttonHesapla.setStyleSheet("QPushButton { \n"
"    border-radius: 20px;\n"
"    border-style: outset; \n"
"    padding: 5px;\n"
"    color: #fff;\n"
"    background-color: #5865F2;\n"
"    }\n"
" ")
        self.buttonHesapla.setObjectName("buttonHesapla")
        self.buttonBir = QtWidgets.QPushButton(Dialog)
        self.buttonBir.setGeometry(QtCore.QRect(20, 170, 50, 50))
        self.buttonBir.setStyleSheet("QPushButton {\n"
"    color: #fff; \n"
"    border-radius: 20px;\n"
"    border-style: outset; \n"
"    padding: 5px;\n"
"    background-color: #141414;\n"
"    }\n"
" ")
        self.buttonBir.setObjectName("buttonBir")
        self.buttonUc = QtWidgets.QPushButton(Dialog)
        self.buttonUc.setGeometry(QtCore.QRect(140, 170, 50, 50))
        self.buttonUc.setStyleSheet("QPushButton {\n"
"    color: #fff; \n"
"    border-radius: 20px;\n"
"    border-style: outset; \n"
"    padding: 5px;\n"
"    background-color: #141414;\n"
"    }\n"
" ")
        self.buttonUc.setObjectName("buttonUc")
        self.buttonIki = QtWidgets.QPushButton(Dialog)
        self.buttonIki.setGeometry(QtCore.QRect(80, 170, 50, 50))
        self.buttonIki.setStyleSheet("QPushButton {\n"
"    color: #fff; \n"
"    border-radius: 20px;\n"
"    border-style: outset; \n"
"    padding: 5px;\n"
"    background-color: #141414;\n"
"    }\n"
" ")
        self.buttonIki.setObjectName("buttonIki")
        self.buttonDokuz = QtWidgets.QPushButton(Dialog)
        self.buttonDokuz.setGeometry(QtCore.QRect(140, 290, 50, 50))
        self.buttonDokuz.setStyleSheet("QPushButton {\n"
"    color: #fff; \n"
"    border-radius: 20px;\n"
"    border-style: outset; \n"
"    padding: 5px;\n"
"    background-color: #141414;\n"
"    }\n"
" ")
        self.buttonDokuz.setObjectName("buttonDokuz")
        self.buttonYedi = QtWidgets.QPushButton(Dialog)
        self.buttonYedi.setGeometry(QtCore.QRect(20, 290, 50, 50))
        self.buttonYedi.setStyleSheet("QPushButton {\n"
"    color: #fff; \n"
"    border-radius: 20px;\n"
"    border-style: outset; \n"
"    padding: 5px;\n"
"    background-color: #141414;\n"
"    }\n"
" ")
        self.buttonYedi.setObjectName("buttonYedi")
        self.buttonSekiz = QtWidgets.QPushButton(Dialog)
        self.buttonSekiz.setGeometry(QtCore.QRect(80, 290, 50, 50))
        self.buttonSekiz.setStyleSheet("QPushButton {\n"
"    color: #fff; \n"
"    border-radius: 20px;\n"
"    border-style: outset; \n"
"    padding: 5px;\n"
"    background-color: #141414;\n"
"    }\n"
" ")
        self.buttonSekiz.setObjectName("buttonSekiz")
        self.buttonAlti = QtWidgets.QPushButton(Dialog)
        self.buttonAlti.setGeometry(QtCore.QRect(140, 230, 50, 50))
        self.buttonAlti.setStyleSheet("QPushButton {\n"
"    color: #fff; \n"
"    border-radius: 20px;\n"
"    border-style: outset; \n"
"    padding: 5px;\n"
"    background-color: #141414;\n"
"    }\n"
" ")
        self.buttonAlti.setObjectName("buttonAlti")
        self.buttonDort = QtWidgets.QPushButton(Dialog)
        self.buttonDort.setGeometry(QtCore.QRect(20, 230, 50, 50))
        self.buttonDort.setStyleSheet("QPushButton {\n"
"    color: #fff; \n"
"    border-radius: 20px;\n"
"    border-style: outset; \n"
"    padding: 5px;\n"
"    background-color: #141414;\n"
"    }\n"
" ")
        self.buttonDort.setObjectName("buttonDort")
        self.buttonBes = QtWidgets.QPushButton(Dialog)
        self.buttonBes.setGeometry(QtCore.QRect(80, 230, 50, 50))
        self.buttonBes.setStyleSheet("QPushButton {\n"
"    color: #fff; \n"
"    border-radius: 20px;\n"
"    border-style: outset; \n"
"    padding: 5px;\n"
"    background-color: #141414;\n"
"    }\n"
" ")
        self.buttonBes.setObjectName("buttonBes")
        self.pushButton_17 = QtWidgets.QPushButton(Dialog)
        self.pushButton_17.setGeometry(QtCore.QRect(140, 110, 50, 50))
        self.pushButton_17.setStyleSheet("QPushButton { \n"
"    border-radius: 20px;\n"
"    border-style: outset; \n"
"    padding: 5px;\n"
"    background-color: #fff;\n"
"    }\n"
" ")
        self.pushButton_17.setObjectName("pushButton_17")
        self.buttonSifir = QtWidgets.QPushButton(Dialog)
        self.buttonSifir.setGeometry(QtCore.QRect(20, 350, 171, 50))
        self.buttonSifir.setStyleSheet("QPushButton { \n"
"    border-radius: 20px;\n"
"    border-style: outset; \n"
"    padding: 5px;\n"
"    color: #fff;\n"
"    background-color: #141414;\n"
"    }\n"
" ")
        self.buttonSifir.setObjectName("buttonSifir")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 30, 211, 61))
        self.label.setStyleSheet("color: #fff;\n"
"background: transparent;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Hesap Makinesi - By TheClawNz#7987"))
        self.buttonSifirla.setText(_translate("Dialog", "C"))
        self.pushButton_2.setText(_translate("Dialog", "<="))
        self.buttonArti.setText(_translate("Dialog", "+"))
        self.buttonBol.setText(_translate("Dialog", "/"))
        self.buttonCarp.setText(_translate("Dialog", "*"))
        self.buttonEksi.setText(_translate("Dialog", "-"))
        self.buttonHesapla.setText(_translate("Dialog", "="))
        self.buttonSifir.setText(_translate("Dialog", "0"))
        self.buttonBir.setText(_translate("Dialog", "1"))
        self.buttonIki.setText(_translate("Dialog", "2"))
        self.buttonUc.setText(_translate("Dialog", "3"))
        self.buttonDort.setText(_translate("Dialog", "4"))
        self.buttonBes.setText(_translate("Dialog", "5"))
        self.buttonAlti.setText(_translate("Dialog", "6"))
        self.buttonYedi.setText(_translate("Dialog", "7"))
        self.buttonDokuz.setText(_translate("Dialog", "9"))
        self.buttonSekiz.setText(_translate("Dialog", "8"))
        self.pushButton_17.setText(_translate("Dialog", "%"))
        self.label.setText(_translate("Dialog", "0"))
